"use client"

import { Button } from "@/components/ui/button"
import { Sparkles, ArrowRight, ShieldCheck, ClipboardList, Info } from "lucide-react"

export function LandingView({ onStart, onAbout }: { onStart: () => void; onAbout: () => void }) {
  return (
    <main className="min-h-screen bg-background text-foreground flex flex-col justify-between selection:bg-primary/20">
      
      {/* Premium Apple-Style Navigation Bar */}
      <header className="max-w-6xl w-full mx-auto px-6 py-6 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="h-6 w-6 rounded-full bg-primary flex items-center justify-center text-primary-foreground font-bold">
            <Sparkles className="h-3.5 w-3.5" />
          </div>
          <span className="font-semibold text-base tracking-tight text-white font-sans">
            OpenCognitive
          </span>
        </div>
        <div className="flex items-center gap-5">
          <button
            onClick={onAbout}
            className="text-sm font-semibold text-muted-foreground hover:text-white transition-colors cursor-pointer"
          >
            About
          </button>
        </div>
      </header>

      {/* Hero Section */}
      <section className="max-w-4xl w-full mx-auto px-6 py-12 md:py-20 flex flex-col items-center text-center space-y-10">
        
        {/* Editorial Heading */}
        <div className="space-y-4 max-w-2xl">
          <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-white leading-[1.1]">
            A transparent measure of human reasoning.
          </h1>
          <p className="text-lg sm:text-xl text-muted-foreground font-normal leading-relaxed">
            Measure fluid intelligence and visuospatial rotation through a clinically calibrated, open-source psychometric instrument.
          </p>
        </div>

        {/* Student Research Disclaimer */}
        <div className="bg-amber-500/5 border border-amber-500/20 px-6 py-4 rounded-2xl max-w-2xl text-xs text-amber-200/80 leading-relaxed text-center font-sans">
          <span className="font-bold text-amber-400 uppercase tracking-wider block mb-1">Student Research Project Disclaimer</span>
          This tool is a student project developed for educational research in cognitive psychometrics. 
          The estimated scores generated by this instrument are illustrative simulations and <strong>must never be used as a substitute for professional clinical testing or diagnostic evaluation</strong> by a licensed psychologist.
        </div>

        {/* Call to action & parameters */}
        <div className="flex flex-col sm:flex-row items-center gap-4 w-full justify-center">
          <Button
            onClick={onStart}
            size="lg"
            className="w-full sm:w-auto h-14 rounded-full px-8 text-base font-semibold bg-white hover:bg-neutral-200 text-black transition-all duration-200 shadow-lg cursor-pointer"
          >
            Start Assessment
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
          <div className="text-sm font-medium text-muted-foreground flex items-center gap-2">
            <span>24 items</span>
            <span className="h-1 w-1 bg-muted-foreground rounded-full" />
            <span>~12 minutes</span>
          </div>
        </div>

        {/* Feature Cards in Premium Minimal Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full pt-10 text-left">
          
          <div className="p-6 bg-card rounded-xl border border-border space-y-3 glow-card">
            <div className="h-9 w-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
              <ShieldCheck className="h-5 w-5" />
            </div>
            <h3 className="text-base font-semibold text-white">Privacy Secured</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Calculations run entirely in your local browser. No response harvesting or account logins.
            </p>
          </div>

          <div className="p-6 bg-card rounded-xl border border-border space-y-3 glow-card">
            <div className="h-9 w-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
              <ClipboardList className="h-5 w-5" />
            </div>
            <h3 className="text-base font-semibold text-white">Diverse Scales</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Covers Matrix Reasoning, 3D Rotation, Letter/Number sequences, and Verbal Syllogisms.
            </p>
          </div>

          <div className="p-6 bg-card rounded-xl border border-border space-y-3 glow-card">
            <div className="h-9 w-9 rounded-lg bg-primary/10 text-primary flex items-center justify-center">
              <Info className="h-5 w-5" />
            </div>
            <h3 className="text-base font-semibold text-white">IRT Bayesian Scoring</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Uses calibrated 2PL/3PL models and EAP ability scoring to estimate latent theta (θ).
            </p>
          </div>

        </div>

      </section>

      {/* Footer status bar */}
      <footer className="max-w-6xl w-full mx-auto px-6 py-8 border-t border-border flex flex-col sm:flex-row items-center justify-between text-xs text-muted-foreground gap-4">
        <div className="flex flex-col sm:flex-row items-center gap-2 sm:gap-4">
          <span>Developed by Ritesh. No paywalls. Built for research.</span>
          <span className="hidden sm:inline text-border">|</span>
          <a 
            href="https://github.com/riteshrajas/OpenCognitive" 
            target="_blank" 
            rel="noopener noreferrer" 
            className="hover:text-white transition-colors underline underline-offset-4"
          >
            GitHub Repository
          </a>
        </div>
        <span>Open Science Framework compliant.</span>
      </footer>

    </main>
  )
}
